name: Github Pages

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Check Dependencies
        run: |
          pnpm list --recursive
          pnpm licenses list
          pnpm outdated --recursive

      - name: Check pnpm
        run: |
          pnpm doctor

      - name: Build Docs
        run: |
          pnpm run build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/.vitepress/dist
          cname: docs.sublimetext.io
